version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      - JWT_SECRET=7b1798c92291111f618d256e52cd30fda6e1eca0b25c2a243c1af4b5477b0047
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - postgres
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres:17
    ports:
      - "5433:5432"  # Corrigido: expõe 5432 do container na 5433 do host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
